name: PR Sanity Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      statuses: write
      contents: write
      pull-requests: write # 'write' access to pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.GITHUB_HEAD_REF }}

      - name: Install Packages
        run: |
          npm install

      - name: Lint check
        run: |
          npm run lint

      - name: Test check
        run: |
          npm run test

      - name: Check total coverage
        run: npx check-total --min 60

      - name: Update code coverage badge
        run: |
          DEBUG=check-code-coverage npx update-badge
          git status

      # - name: Set code coverage commit status
      # run: |
      #   DEBUG=check-code-coverage npx set-gh-status
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        run: |
          git config --local user.email "test@test.com"
          git config --local user.name "Test"
          git commit -a -m "Add changes"
          git push origin $GITHUB_HEAD_REF --force

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
