name: PR Sanity Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Packages
        run: |
          npm install

      - name: Lint check
        run: |
          npm run lint

      - name: Test check
        run: |
          npm run test

      - name: Check total coverage
        run: npx check-total --min 60

      - name: Set code coverage commit status
        run: npx set-gh-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update code coverage badge
        run: npx update-badge
