name: PR Sanity Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      statuses: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Packages
        run: |
          npm install

      - name: Lint check
        run: |
          npm run lint

      - name: Test check
        run: |
          npm run test

      - name: Check total coverage
        run: npx check-total --min 60

      - name: Update code coverage badge
        run: |
          DEBUG=check-code-coverage npx update-badge

      # - name: Set code coverage commit status
      # run: |
      #   DEBUG=check-code-coverage npx set-gh-status
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}]
          force_with_lease: true
