name: PR Sanity Check

on: 
  - pull_request
  - push

jobs:
  lint:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      statuses: write
      contents: write
      pull-requests: write # 'write' access to pull requests
    env:
      COVERALLS_REPO_TOKEN: zr2d2c9OVbmf5gIMogppFR0ytVWarIaZU
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.GITHUB_HEAD_REF }}

      - name: Install Packages
        run: |
          npm install

      - name: Lint check
        run: |
          npm run lint

      - name: Test check
        run: |
          npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          debug: true
